### ISSUE TITLE
Cannot generate one WMTS capabilities per instance

### ISSUE THREAD

**Issue by rbovard** [camptocamp/c2cgeoportal#2081]
Following instructions in #2002, the file created is always named `WMTSCapabilities.xml` (and not `WMTSCapabilities-xxx.xml`) even if on `project-clean` it's a file named `WMTSCapabilities-xxx.xml` which is deleted.

**Comment by yjacolin** [comment]
The PR you link to is tagged 1.6.8 which is not released yet.

**Comment by sbrunner** [comment]
Docs should be complete with:

Your right it's more complicated, in your tilegeneration config you should add in the cache:
`wmtscapabilities_file: ${wmtscapabilities_file}`
in the project vars file: 
```yaml
vars:
    ...
    wmtscapabilities_file: WMTSCAPABILITIES_FILE
interpreted:
    ...
    environment:
    ...
    - wmtscapabilities_file
```
and in the project Makefile:
```
ENVIRONMENT_VARS += WMTSCAPABILITIES_FILE=$(WMTSCAPABILITIES_FILE)
```
