### ISSUE TITLE
[print] default layout and config

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/c2cgeoportal#304]
c2cgeoportal should contains correct default print setting and layout mainly used by our customers:
- nice legend (option) in 2nd page
- A4 and A3 page size and landscape and portrait layout

Peitrequin or jourdan instance could be used as default setting and layout (jourdan is much better: https://project.camptocamp.com/svn/jourdan_cw3/c2cgeoportal/puidoux/print/)

Add odg files in print directory to allow integrator to change easily the PDF template.

Legend config:

```
    lastPage:
      pageSize: A4
      items:
        - !columns
          condition: legends
          absoluteX: 51
          absoluteY: 700
          width: 511
          backgroundColor: #FF0000
          items:
            - !text
              align:left
              text: 'Légende'
              spacingAfter: 10
        - !columns
          condition: legends
          absoluteX: 51
          absoluteY: 680
          width: 400
          backgroundColor: #FF0000
          items:
            - !legends
              inline: false
              defaultScale: 0.5
              maxHeight: 550
              maxWidth: 50
              maxIconHeight: 0
              maxIconWidth: 0
              columnMargin: 5
              classIndentation: 3
              classSpace: 5
              layerSpace: 5
              backgroundColor: white
```
